app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

// Staff (Sub-Domain for Control Panel)
Route::group(['domain' => 'staff.' . env('APP_DOMAIN', 'hackersir2.localhost')], function () {
    //Index
    Route::get('/', [
        'as' => 'staff.index',
        'uses' => 'StaffController@index',
    ]);
    //Auth System
    Route::controller('user', 'UserController', [
        'getIndex' => 'user.list',
        'getLogin' => 'user.login',
        'postLogin' => 'user.login',
        'getRegister' => 'user.register',
        'postRegister' => 'user.register',
        'getConfirm' => 'user.confirm',
        'getResend' => 'user.resend',
        'postResend' => 'user.resend',
        'getForgotPassword' => 'user.forgot-password',
        'postForgotPassword' => 'user.forgot-password',
        'getResetPassword' => 'user.reset-password',
        'postResetPassword' => 'user.reset-password',
        'getChangePassword' => 'user.change-password',
        'postChangePassword' => 'user.change-password',
        'getProfile' => 'user.profile',
        'getEditProfile' => 'user.edit-profile',
        'postEditProfile' => 'user.edit-profile',
        'getEditOtherProfile' => 'user.edit-other-profile',
        'postEditOtherProfile' => 'user.edit-other-profile',
        'getLogout' => 'user.logout'
    ]);

    //UserMail
    Route::resource('user-mail', 'UserMailController', ['only' => ['index', 'store', 'destroy']]);

    // Member
    Route::post('member/addNID/{id}', [
        'as' => 'member.add-nid',
        'uses' => 'MemberController@addNID'
    ]);
    Route::delete('member/removeNID/{id}', [
        'as' => 'member.remove-nid',
        'uses' => 'MemberController@removeNID'
    ]);
    Route::get('member/check-link', [
        'as' => 'member.check-link',
        'uses' => 'MemberController@getCheckLink'
    ]);
    Route::post('member/update-link', [
        'as' => 'member.update-link',
        'uses' => 'MemberController@postUpdateLink'
    ]);
    Route::resource('member', 'MemberController');


    // Setting
//    Route::controller('setting', 'SettingController', array(
//        'getIndex' => 'setting.index',
//
//    ));

    // Issue
    Route::controller('issue', 'IssueController', [
        'getIndex' => 'issue.index',

    ]);

    // Agenda
//    Route::controller('agenda', 'CalendarController', array(
//        'getIndex' => 'agenda.index',
//    ));

    // Document
    Route::resource('document', 'DocumentController');

    // Financial
    //Route::resource('financial', 'FinancialController');

    // Cadre
    Route::resource('cadre', 'CadreController', ['except' => ['index', 'show']]);

    // Announcement
    Route::resource('announcement', 'AnnouncementController');

    //Log Viewer
    Route::get('log', [
        'as' => 'log',
        'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index',
        'middleware' => 'role:admin'
    ]);

    // Undefined
    Route::get('{all}', [
        'as' => 'not-found',
        function () {
            abort(404);
        }
    ])->where('all', '.*');
});

// Index (for guest)
Route::get('/', [
    'as' => 'home',
    'uses' => 'HomeController@index'
]);

// Announce
Route::resource('announce', 'EnterPageController', ['only' => ['index', 'show']]);

// About
Route::controller('about', 'AboutController', [
    'getIndex' => 'about.index',
    'getClub' => 'about.club',
    'getCadre' => 'about.cadre',
    'getMilestone' => 'about.milestone',
    'getRule' => 'about.rule',
    'getFinancial' => 'about.financial',
    'getFriend' => 'about.friend',
]);

// Lesson
Route::group(['prefix' => 'lesson'], function () {
    Route::get('regular', [
        'as' => 'lesson.regular',
        function () {
            return view('front.lesson.regular');
        }
    ]);
    Route::get('cooperation', [
        'as' => 'lesson.cooperation',
        function () {
            return view('front.lesson.cooperation');
        }
    ]);
    Route::get('special', [
        'as' => 'lesson.special',
        function () {
            return view('front.lesson.special');
        }
    ]);
});

// Activity
Route::resource('activity', 'ActivityController', ['only' => ['index', 'show']]);

// Policies
Route::group(['prefix' => 'policies'], function () {
    // Terms
    Route::get('terms', [
        'as' => 'policies.terms',
        function () {
            return view('policies.terms');
        }
    ]);
    // Privacy
    Route::get('privacy', [
        'as' => 'policies.privacy',
        function () {
            return view('policies.privacy');
        }
    ]);
});

//Markdown API
Route::any('markdown', [
    'as' => 'markdown.preview',
    'uses' => 'MarkdownApiController@markdownPreview'
]);

// Undefined
Route::get('{all}', [
    'as' => 'not-found',
    function () {
        abort(404);
    }
])->where('all', '.*');

app/Announcement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * 公告
 *
 * @property integer id
 * @property string title
 * @property string message
 * @property \Carbon\Carbon|null start_at
 * @property \Carbon\Carbon|null end_at
 * @property integer|null user_id
 *
 * @property-read User|null user
 *
 * @property \Carbon\Carbon|null created_at
 * @property \Carbon\Carbon|null updated_at
 * @property \Carbon\Carbon|null deleted_at
 */
class Announcement extends Model
{
    //使用軟刪除
    use SoftDeletes;

    /** @var string $table 資料表 */
    protected $table = 'announcements';

    /** @var array $fillable 可大量指派的屬性 */
    protected $fillable = [
        'title',
        'message',
        'start_at',
        'end_at',
        'user_id'
    ];

    /** @var array $dates 自動轉換為Carbon的屬性 */
    protected $dates = ['start_at', 'end_at'];

    /** @var integer 分頁時的每頁數量 */
    protected $perPage = 20;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/AnnouncementController.php
<?php

namespace App\Http\Controllers;

use App\Announcement;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;

class AnnouncementController extends Controller
{
    /**
     * AnnouncementController constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->middleware('role:admin', [
            'except' => [
                'index',
                'show'
            ]
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //FIXME: 排列依據需修改，若已開始時間排序，須考慮到無開始時間之公告
        $announcements = Announcement::with('user')->orderBy('id', 'desc')->paginate();
        return view('announcement.index', compact('announcements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('announcement.create-or-edit')->with('methodText', '新增');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'start_at' => 'date',
            'end_at' => 'date|after:start_at',
            'message' => 'required|max:65535'
        ]);

        $announcement = Announcement::create([
            'title' => $request->get('title'),
            'start_at' => $request->get('start_at') ?: null,
            'end_at' => $request->get('end_at') ?: null,
            'message' => $request->get('message'),
            'user_id' => Auth::user()->id
        ]);

        return redirect()->route('announcement.show', $announcement)->with('global', '公告已建立');
    }

    /**
     * Display the specified resource.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $announcement = Announcement::find($id);
        if (!$announcement) {
            return Redirect::route('announcement.index')
                ->with('warning', '公告不存在');
        }
        return view('announcement.show', compact('announcement'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $announcement = Announcement::find($id);
        if (!$announcement) {
            return Redirect::route('announcement.index')
                ->with('warning', '公告不存在');
        }
        return view('announcement.create-or-edit', compact('announcement'))->with('methodText', '修改');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $announcement = Announcement::find($id);
        if (!$announcement) {
            return Redirect::route('announcement.index')
                ->with('warning', '公告不存在');
        }
        $this->validate($request, [
            'title' => 'required|max:255',
            'start_at' => 'date',
            'end_at' => 'date|after:start_at',
            'message' => 'required|max:65535'
        ]);

        $announcement->title = $request->get('title');
        $announcement->start_at = $request->get('start_at') ?: null;
        $announcement->end_at = $request->get('end_at') ?: null;
        $announcement->message = $request->get('message');
        $announcement->save();

        return redirect()->route('announcement.show', $announcement)->with('global', '公告已更新');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $announcement = Announcement::find($id);
        if (!$announcement) {
            return Redirect::route('announcement.index')
                ->with('warning', '公告不存在');
        }
        $announcement->delete();
        return redirect()->route('announcement.index')->with('global', '公告已刪除');
    }
}

resources/views/announcement/create-or-edit.blade.php
@extends('app')

@section('title', $methodText. '公告')

@section('css')
    {!! HTML::style('css/bootstrap-datetimepicker.css') !!}
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="well">
                    @if(isset($announcement))
                        {!! BootForm::openHorizontal(['sm' => [5, 7], 'lg' => [2, 10]])
                            ->action(route('announcement.update', $announcement))->put() !!}
                        {!! BootForm::bind($announcement) !!}
                    @else
                        {!! BootForm::openHorizontal(['sm' => [5, 7], 'lg' => [2, 10]])
                            ->action(route('announcement.store')) !!}
                    @endif
                    <fieldset>
                        <legend>{{ $methodText }}公告</legend>
                        {!! BootForm::text('標題', 'title')->required() !!}
                        {{-- 開始時間 --}}
                        <div class="form-group has-feedback{{ ($errors->has('start_at'))?' has-error':'' }}">
                            {!! Form::label('start_at', '開始時間', ['class' => 'control-label col-sm-5 col-lg-2']) !!}
                            <div class="col-sm-7 col-lg-10">
                                <div class='input-group date datetimepicker'>
                                    {{-- 由於 model bind 是在 BootForm 上， Form要自行帶入 --}}
                                    {!! Form::text('start_at', isset($announcement) ? $announcement->start_at : null, ['id' => 'start_at', 'placeholder' => 'YYYY-MM-DD HH:mm:ss', 'class' => 'form-control']) !!}
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                                @if($errors->has('start_at'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                <span class="label label-danger">{{ $errors->first('start_at') }}</span>@endif
                            </div>
                        </div>
                        {{-- 結束時間 --}}
                        <div class="form-group has-feedback{{ ($errors->has('end_at'))?' has-error':'' }}">
                            {!! Form::label('end_at', '結束時間', ['class' => 'control-label col-sm-5 col-lg-2']) !!}
                            <div class="col-sm-7 col-lg-10">
                                <div class='input-group date datetimepicker'>
                                    {{-- 由於 model bind 是在 BootForm 上， Form要自行帶入 --}}
                                    {!! Form::text('end_at', isset($announcement) ? $announcement->end_at : null, ['id' => 'end_at', 'placeholder' => 'YYYY-MM-DD HH:mm:ss', 'class' => 'form-control']) !!}
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                                @if($errors->has('end_at'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                                <span class="label label-danger">{{ $errors->first('end_at') }}</span>@endif
                            </div>
                        </div>
                        {{--公告內容(Markdown) --}}
                        @include('common.markdown', [
                            'name' => 'message',
                            'labelName' => '內容',
                            'text' => isset($announcement) ? $announcement->message : null
                        ])
                        {{-- 提交按鈕 --}}
                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-7 col-lg-offset-2 col-lg-10">
                                {!! Form::submit($methodText, ['class' => 'btn btn-primary']) !!}
                                @if(isset($announcement))
                                    <a href="{{ route('announcement.show', $announcement) }}" class="btn btn-default">返回</a>
                                @else
                                    <a href="{{ route('announcement.index') }}" class="btn btn-default">返回</a>
                                @endif
                            </div>
                        </div>
                    </fieldset>
                    {!! BootForm::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    {!! HTML::script('//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js') !!}
    {!! HTML::script('js/moment_zh-tw.js') !!}
    {!! HTML::script('js/bootstrap-datetimepicker.min.js') !!}
    <script type="text/javascript">
        $(function () {
            $('.datetimepicker').each(function () {
                $(this).datetimepicker({
                    format: 'YYYY-MM-DD HH:mm:ss'
                });
            });
        });
    </script>
    @include('common.markdown-js', ['name' => 'message'])
@endsection

resources/views/announcement/index.blade.php
@extends('app')

@section('title', '網站公告')

@section('content')
    <div class="container">
        @role('admin')
        <a href="{{ route('announcement.create') }}" class="btn btn-primary"><i class="fa fa-plus-square"></i> 新增公告</a>
        @endrole
        <div class="page-header">
            <h1>網站公告</h1>
        </div>
        <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
                <th class="text-center col-md-8">標題</th>
                <th class="text-center col-md-2">開始時間</th>
                <th class="text-center col-md-2">結束時間</th>
            </tr>
            </thead>
            <tbody>
            @foreach($announcements as $announcement)
                <tr>
                    <td>
                        {!! link_to_route('announcement.show', $announcement->title, $announcement) !!}
                    @if($announcement->user)
                        <span class="pull-right"><i class="fa fa-pencil"></i>
                            @if(Entrust::hasRole('admin'))
                                {!! link_to_route('user.profile', $announcement->user->getNickname(), $announcement->user) !!}
                            @else
                                {{ $announcement->user->getNickname() }}
                            @endif
                        </span>
                        @endif
                    </td>
                    <td>{{ $announcement->start_at }}</td>
                    <td>{{ $announcement->end_at }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <div class="text-center">
        {!! $announcements->appends(Request::except(['page']))->render() !!}
    </div>
@endsection

resources/views/announcement/show.blade.php
@extends('app')

@section('title', $announcement->title)

@section('content')
    <div class="container">
        <a href="{{ route('announcement.index') }}" class="btn btn-default" role="button"><i class="fa fa-arrow-left"></i> 返回網站公告</a>
        @role('admin')
        <a href="{{ route('announcement.edit', $announcement) }}" class="btn btn-primary" role="button"><i class="fa fa-cogs"></i> 編輯公告</a>
        {!! Form::open(['route' => ['announcement.destroy', $announcement], 'style' => 'display: inline', 'method' => 'DELETE', 'onSubmit' => "return confirm('確定要刪除此公告嗎？');"]) !!}
        <button type="submit" class="btn btn-danger">
            <i class="fa fa-trash"></i> 刪除公告
        </button>
        {!! Form::close() !!}
        @endrole
        <div class="page-header">
            <h1>{{ $announcement->title }}</h1>
        </div>
        <blockquote>
            @if($announcement->user)
            <div class="row">
                <div class="col-md-2">發布者：</div>
                <div><i class="fa fa-pencil"></i>
                    @if(Entrust::hasRole('admin'))
                        {!! link_to_route('user.profile', $announcement->user->getNickname(), $announcement->user) !!}
                    @else
                        {{ $announcement->user->getNickname() }}
                    @endif
                </div>
            </div>
            @endif
            <div class="row">
                <div class="col-md-2">開始時間：</div>
                <div>{{ $announcement->start_at or '（未指定）' }}</div>
            </div>
            <div class="row">
                <div class="col-md-2">結束時間：</div>
                <div>{{ $announcement->end_at or '（未指定）' }}</div>
            </div>
        </blockquote>
        <blockquote>
            {!! App\Helper\MarkdownHelper::translate($announcement->message) !!}
        </blockquote>
    </div>
@endsection