app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

// Staff (Sub-Domain for Control Panel)
Route::group(['domain' => 'staff.' . env('APP_DOMAIN', 'hackersir2.localhost')], function () {
    //Index
    Route::get('/', [
        'as' => 'staff.index',
        'uses' => 'StaffController@index',
    ]);
    //Auth System
    Route::controller('user', 'UserController', [
        'getIndex' => 'user.list',
        'getLogin' => 'user.login',
        'postLogin' => 'user.login',
        'getRegister' => 'user.register',
        'postRegister' => 'user.register',
        'getConfirm' => 'user.confirm',
        'getResend' => 'user.resend',
        'postResend' => 'user.resend',
        'getForgotPassword' => 'user.forgot-password',
        'postForgotPassword' => 'user.forgot-password',
        'getResetPassword' => 'user.reset-password',
        'postResetPassword' => 'user.reset-password',
        'getChangePassword' => 'user.change-password',
        'postChangePassword' => 'user.change-password',
        'getProfile' => 'user.profile',
        'getEditProfile' => 'user.edit-profile',
        'postEditProfile' => 'user.edit-profile',
        'getEditOtherProfile' => 'user.edit-other-profile',
        'postEditOtherProfile' => 'user.edit-other-profile',
        'getLogout' => 'user.logout'
    ]);

    //UserMail
    Route::resource('user-mail', 'UserMailController', ['only' => ['index', 'store', 'destroy']]);

    // Member
    Route::post('member/addNID/{id}', [
        'as' => 'member.add-nid',
        'uses' => 'MemberController@addNID'
    ]);
    Route::delete('member/removeNID/{id}', [
        'as' => 'member.remove-nid',
        'uses' => 'MemberController@removeNID'
    ]);
    Route::get('member/check-link', [
        'as' => 'member.check-link',
        'uses' => 'MemberController@getCheckLink'
    ]);
    Route::post('member/update-link', [
        'as' => 'member.update-link',
        'uses' => 'MemberController@postUpdateLink'
    ]);
    Route::resource('member', 'MemberController');


    // Setting
//    Route::controller('setting', 'SettingController', array(
//        'getIndex' => 'setting.index',
//
//    ));

    // Issue
    Route::controller('issue', 'IssueController', [
        'getIndex' => 'issue.index',

    ]);

    // Agenda
//    Route::controller('agenda', 'CalendarController', array(
//        'getIndex' => 'agenda.index',
//    ));

    // Document
    Route::resource('document', 'DocumentController');

    // Financial
    //Route::resource('financial', 'FinancialController');

    // Cadre
    Route::resource('cadre', 'CadreController', ['except' => ['index', 'show']]);

    // Announcement
    Route::resource('announcement', 'AnnouncementController');

    //Log Viewer
    Route::get('log', [
        'as' => 'log',
        'uses' => '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index',
        'middleware' => 'role:admin'
    ]);

    // Undefined
    Route::get('{all}', [
        'as' => 'not-found',
        function () {
            abort(404);
        }
    ])->where('all', '.*');
});

// Index (for guest)
Route::get('/', [
    'as' => 'home',
    'uses' => 'HomeController@index'
]);

// Announce
Route::resource('announce', 'EnterPageController', ['only' => ['index', 'show']]);

// About
Route::controller('about', 'AboutController', [
    'getIndex' => 'about.index',
    'getClub' => 'about.club',
    'getCadre' => 'about.cadre',
    'getMilestone' => 'about.milestone',
    'getRule' => 'about.rule',
    'getFinancial' => 'about.financial',
    'getFriend' => 'about.friend',
]);

// Lesson
Route::group(['prefix' => 'lesson'], function () {
    Route::get('regular', [
        'as' => 'lesson.regular',
        function () {
            return view('front.lesson.regular');
        }
    ]);
    Route::get('cooperation', [
        'as' => 'lesson.cooperation',
        function () {
            return view('front.lesson.cooperation');
        }
    ]);
    Route::get('special', [
        'as' => 'lesson.special',
        function () {
            return view('front.lesson.special');
        }
    ]);
});

// Activity
Route::resource('activity', 'ActivityController', ['only' => ['index', 'show']]);

// Policies
Route::group(['prefix' => 'policies'], function () {
    // Terms
    Route::get('terms', [
        'as' => 'policies.terms',
        function () {
            return view('policies.terms');
        }
    ]);
    // Privacy
    Route::get('privacy', [
        'as' => 'policies.privacy',
        function () {
            return view('policies.privacy');
        }
    ]);
});

//Markdown API
Route::any('markdown', [
    'as' => 'markdown.preview',
    'uses' => 'MarkdownApiController@markdownPreview'
]);

// Undefined
Route::get('{all}', [
    'as' => 'not-found',
    function () {
        abort(404);
    }
])->where('all', '.*');

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;
    use EntrustUserTrait;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email',
        'nickname',
        'password',
        'register_ip',
        'register_at',
        'lastlogin_ip',
        'lastlogin_at'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function member()
    {
        return $this->hasOne('App\Member');
    }

    public function userMails()
    {
        return $this->hasMany('App\UserMail')->orderBy('created_at');
    }

    public function primaryMail()
    {
        return $this->hasOne('App\UserMail')->where('user_id', '=', $this->id)->where('email', '=', $this->email);
    }

    public function isConfirmed()
    {
        if ($this->primaryMail) {
            if ($this->primaryMail->isConfirmed()) {
                return true;
            }
        }
        return false;
    }

    public function getNickname()
    {
        if (!empty($this->nickname)) {
            $nickname = $this->nickname;
        } else {
            $nickname = explode("@", $this->email)[0];
        }
        return $nickname;
    }
}

app/Http/Controllers/UserController.php
<?php namespace App\Http\Controllers;

use App\Helper\JsonHelper;
use App\Helper\LogHelper;
use App\Role;
use App\User;
use App\UserMail;
use Carbon\Carbon;
use GrahamCampbell\Throttle\Facades\Throttle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Validator;
use GuzzleHttp\Client;
use Exception;

class UserController extends Controller
{
    public function __construct()
    {
        parent::__construct();
        //遊客限定
        $this->middleware('guest', [
            'only' => [
                'getLogin',
                'postLogin',
                'getRegister',
                'postRegister',
                'getForgotPassword',
                'postForgotPassword',
                'getResetPassword',
                'postResetPassword'
            ]
        ]);
        //會員限定
        $this->middleware('auth', [
            'only' => [
                'getResend',
                'postResend',
                'getChangePassword',
                'postChangePassword',
                'getProfile',
                'getEditProfile',
                'postEditProfile'
            ]
        ]);
        //需完成信箱驗證
        /*$this->middleware('email', [
            'only' => [
                'getIndex',
            ]
        ]);*/
        //限工作人員
        $this->middleware('role:admin', [
            'only' => [
                'getIndex',
                'getEditOtherProfile',
                'postEditOtherProfile'
            ]
        ]);
    }

    //會員清單
    public function getIndex()
    {
        //取得會員清單
        $amountPerPage = 50;
        //搜尋
        $userQuery = User::query();
        if (Input::has('q')) {
            $q = Input::get('q');
            //模糊匹配
            $q = '%' . $q . '%';
            //搜尋：信箱、暱稱、註解
            $userQuery->where(function ($query) use ($q) {
                $query->where('email', 'like', $q)
                    ->orWhere('nickname', 'like', $q);
            });
        }
        $totalCount = $userQuery->count();
        $userList = $userQuery->paginate($amountPerPage);
        return view('user.list')
            ->with('userList', $userList)
            ->with('amountPerPage', $amountPerPage)
            ->with('totalCount', $totalCount);
    }

    //登入
    public function getLogin()
    {
        $this->markPreviousURL();
        return view('user.login');
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function postLogin(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email',
            'password' => 'required',
        ]);
        //檢查登入冷卻，防止惡意登入
        $throttle = Throttle::get($request, 5, 10);

        //密碼錯誤三次後，追加reCaptcha
        $validator->sometimes('g-recaptcha-response', 'required', function ($input) use ($throttle) {
            return $throttle->count() >= 3;
        });

        if ($validator->fails()) {
            return Redirect::route('user.login')
                ->withErrors($validator)
                ->withInput();
        }
        //檢查登入次數
        if (!$throttle->check()) {
            return Redirect::route('user.login')
                ->with('warning', '嘗試登入過於頻繁，請等待10分鐘。')
                ->with('delay', 10 * 60)
                ->withInput();
        }

        //上線環境再檢查
        if (App::environment('production') && !empty(env('Data_Sitekey'))) {
            //密碼錯誤三次後，追加檢查reCaptcha
            if ($throttle->count() >= 3) {
                $result = $this->tryPassGoogleReCAPTCHA($request);
                if (!(is_bool($result->success) && $result->success)) {
                    LogHelper::info('[reCAPTCHA Failed]', $result);
                    return Redirect::route('user.login')
                        ->with('warning', '沒有通過 reCAPTCHA 驗證，請再試一次。')
                        ->withInput();
                }
            }
        }

        //增加次數
        $throttle->hit();

        $remember = ($request->has('remember')) ? true : false;
        $auth = Auth::attempt([
            'email' => $request->get('email'),
            'password' => $request->get('password'),
        ], $remember);

        if (!$auth) {
            //紀錄
            LogHelper::info('[LoginFailed] 登入失敗：' . $request->get('email'), [
                'email' => $request->get('email'),
                'ip' => $request->getClientIp()
            ]);
            return Redirect::route('user.login')
                ->with('warning', '帳號或密碼錯誤');
        }
        $user = Auth::user();
        //更新資料
        $user->lastlogin_ip = $request->getClientIp();
        $user->lastlogin_at = Carbon::now()->toDateTimeString();
        $user->save();
        //移除重新設定密碼的驗證碼
        DB::table('password_resets')->where('email', '=', $user->email)->delete();
        //記錄
        LogHelper::info('[LoginSucceeded] 登入成功：' . $request->get('email'), [
            'email' => $request->get('email'),
            'ip' => $request->getClientIp()
        ]);
        //重導向至登入前頁面
        if (Session::has('previous-url')) {
            return Redirect::to(Session::get('previous-url'))->with('global', '已順利登入');
        } else {
            return Redirect::intended('/')->with('global', '已順利登入');
        }
    }

    //註冊
    public function getRegister()
    {
        return view('user.register');
    }

    public function postRegister(Request $request)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'email' => 'required|email',
                'password' => 'required|min:6',
                'password_again' => 'required|same:password',
                'g-recaptcha-response' => 'required',
            ]
        );

        if ($validator->fails()) {
            return Redirect::route('user.register')
                ->withErrors($validator)
                ->withInput();
        }
        //上線環境再檢查
        if (App::environment('production') && !empty(env('Data_Sitekey'))) {
            $result = $this->tryPassGoogleReCAPTCHA($request);
            if (!(is_bool($result->success) && $result->success)) {
                LogHelper::info('[reCAPTCHA Failed]', $result);
                return Redirect::route('user.register')
                    ->with('warning', '沒有通過 reCAPTCHA 驗證，請再試一次。')
                    ->withInput();
            }
        }
        //信箱
        $email = $request->get('email');
        if (User::where('email', '=', $email)->count()) {
            return Redirect::route('user.register')
                ->with('warning', '該信箱已被註冊。')
                ->withInput();
        }
        //檢查非主要信箱
        if (UserMail::where('email', '=', $email)->whereNotNull('confirm_at')->count()) {
            return Redirect::route('user.register')
                ->with('warning', '該信箱已被設定為備用信箱。')
                ->withInput();
        }

        $password = $request->get('password');
        //驗證碼
        $code = str_random(60);

        $user = User::create(array(
            'email' => $email,
            'password' => Hash::make($password),
            'register_ip' => $request->getClientIp(),
            'register_at' => Carbon::now()->toDateTimeString()
        ));
        $userMail = UserMail::create([
            'user_id' => $user->id,
            'email' => $email,
            'confirm_code' => $code
        ]);

        if (!$user || !$userMail) {
            return Redirect::route('user.register')
                ->with('warning', '註冊時發生錯誤。');
        }
        //發送驗證信件
        try {
            Mail::queue(
                'emails.confirm',
                [
                    'nickname' => $user->getNickname(),
                    'link' => URL::route('user.confirm', $code)
                ],
                function ($message) use ($user) {
                    $message->to($user->email)->subject("[" . Config::get('site.name') . "] 信箱驗證");
                }
            );
        } catch (Exception $e) {
            //Log
            LogHelper::info('[RegisterFailed] 註冊失敗：無法寄出認證信件給' . $email, [
                'email' => $email,
                'ip' => $request->getClientIp()
            ], $e->getMessage());
            //刪除使用者
            $user->delete();

            return Redirect::route('user.register')
                ->with('warning', '無法寄出認證信件，請檢查信箱是否填寫正確，或是稍後再嘗試。')
                ->withInput();
        }
        //記錄
        LogHelper::info('[RegisterSucceeded] 註冊成功：' . $email, [
            'email' => $email,
            'ip' => $request->getClientIp()
        ]);
        return Redirect::route('home')
            ->with('global', '註冊完成，請至信箱收取驗證信件並啟用帳號。');


    }

    protected function tryPassGoogleReCAPTCHA(Request $request)
    {
        if (App::environment('production')) {
            $clientOptions = [
                'timeout' => 10.0
            ];
        } else {
            $clientOptions = [
                'timeout' => 10.0,
                'verify' => false
            ];
        }
        $client = new Client($clientOptions);

        $response = $client->post(
            'https://www.google.com/recaptcha/api/siteverify',
            [
                'form_params' => [
                    'secret' => env('Secret_Key'),
                    'response' => $request->get('g-recaptcha-response'),
                    'remoteip' => $request->getClientIp(),
                ]
            ]
        );

        return JsonHelper::decode($response->getBody());
    }

    //驗證信箱
    public function getConfirm($token = null)
    {
        $userMail = UserMail::where('confirm_code', '=', $token)->whereNull('confirm_at')->first();

resources/views/user/change-password.blade.php
@extends('app')

@section('title')
    修改密碼
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="well bs-component">
                    {!! Form::open(['route' => 'user.change-password']) !!}
                    <fieldset>
                        <legend>修改密碼</legend>
                    </fieldset>
                    <div class="form-group has-feedback{{ ($errors->has('old_password'))?' has-error':'' }}">
                        <label class="control-label" for="old_password">舊密碼
                            @if($errors->has('old_password'))
                                <span class="label label-danger">{{ $errors->first('old_password') }}</span>
                            @endif
                        </label>
                        {!! Form::password('old_password', ['id' => 'old_password', 'placeholder' => '請輸入舊密碼', 'class' => 'form-control', 'required']) !!}
                        @if($errors->has('old_password'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>@endif
                    </div>
                    <div class="form-group has-feedback{{ ($errors->has('password'))?' has-error':'' }}">
                        <label class="control-label" for="password">新密碼
                            @if($errors->has('password'))
                                <span class="label label-danger">{{ $errors->first('password') }}</span>
                            @endif
                        </label>
                        {!! Form::password('password', ['id' => 'password', 'placeholder' => '請輸入新密碼', 'class' => 'form-control', 'required']) !!}
                        @if($errors->has('password'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>@endif
                    </div>
                    <div class="form-group has-feedback{{ ($errors->has('password_again'))?' has-error':'' }}">
                        <label class="control-label" for="password_again">新密碼（再輸入一次）
                            @if($errors->has('password_again'))
                                <span class="label label-danger">{{ $errors->first('password_again') }}</span>
                            @endif
                        </label>
                        {!! Form::password('password_again', ['id' => 'password_again', 'placeholder' => '請再輸入一次新密碼', 'class' => 'form-control', 'required']) !!}
                        @if($errors->has('password_again'))<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>@endif
                    </div>
                    {!! Form::submit('修改密碼', ['class' => 'btn btn-primary']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/user/list.blade.php
@extends('app')

@section('title')
    成員清單
@endsection

@section('css')
    <style type="text/css">
        {{-- 使表格文字垂直置中 --}}
        .table > tbody > tr > td {
            vertical-align: middle;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0">
                <div class="panel panel-default">
                    <div class="panel-heading">成員清單</div>
                    <div class="panel-body">
                        <div class="row" style="margin-bottom: 10px;">
                            <div class="col-md-5">
                                {!! Form::open(['route' => 'user.list', 'class' => 'form-horizontal', 'method' => 'GET']) !!}
                                <div class="input-group">
                                    {!! Form::text('q', Input::get('q'), ['id' => 'q', 'placeholder' => '搜尋信箱、暱稱...', 'class' => 'form-control', 'required']) !!}
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-primary" title="搜尋"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                                        @if(Input::has('q'))
                                            <a class="btn btn-default" href="{{ URL::current() }}" title="清除搜尋結果"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                        @endif
                                    </span>
                                </div>
                                {!! Form::close() !!}
                            </div>
                            <div class="col-md-7">
                                @if(Input::has('q'))
                                    @if($userList->count())
                                        符合「{{ Input::get('q') }}」的資料共 {{ $totalCount }} 筆
                                    @else
                                        找不到符合「{{ Input::get('q') }}」的資料
                                    @endif
                                @endif
                            </div>
                        </div>

                        <table class="table table-hover table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>信箱</th>
                                <th>暱稱</th>
                                <th>群組</th>
                                <th>社員資料</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($userList as $key => $userItem)
                                <tr>
                                    <td>{{ (Input::get('page',1) - 1) * $amountPerPage + $key + 1}}</td>
                                    <td>
                                        <img src="{{ Gravatar::src($userItem->email, 40) }}" class="img-circle" />
                                        <a href="{{ URL::route('user.profile',$userItem->id) }}">{{ $userItem->email }}</a>
                                        @if($userItem->isConfirmed())
                                            <span class="label label-success">已驗證</span>
                                        @else
                                            <span class="label label-danger">未驗證</span>
                                        @endif
                                    </td>
                                    <td>
                                        {{ $userItem->nickname }}
                                    </td>
                                    <td>
                                        @foreach($userItem->roles as $role)
                                            {{ $role->display_name }}<br />
                                        @endforeach
                                    </td>
                                    <td>
                                        @if($userItem->member)
                                            <a href="{{ URL::route('member.show', $userItem->member->id) }}">
                                                {{ $userItem->member->realname }}
                                                @if($userItem->member->nickname)
                                                    （{{ $userItem->member->nickname }}）
                                                @endif
                                            </a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="text-center">
                            {!! str_replace('/?', '?', $userList->appends(Input::except(['page']))->render()) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/other-profile.blade.php
@extends('app')

@section('title')
    {{ $showUser->getNickname() }} - 個人資料
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $showUser->getNickname() }} - 個人資料</div>
                    {{-- Panel body --}}
                    <div class="panel-body">
                        <div class="row">
                            <div class="text-center">
                                {{-- Gravatar大頭貼 --}}
                                <img src="{{ Gravatar::src($showUser->email, 200) }}" class="img-circle" /><br />
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="text-center col-md-10 col-md-offset-1">
                                <table class="table table-hover">
                                    <tr>
                                        <td>Email：</td>
                                        <td>
                                            @foreach($showUser->userMails as $userMail)
                                                {{ $userMail->email }}
                                                @if($userMail->isPrimary())
                                                    <span class="label label-info">主要</span>
                                                @endif
                                                @if($userMail->isConfirmed())
                                                    <span class="label label-success">已驗證</span>
                                                @else
                                                    <span class="label label-danger">未驗證</span>
                                                @endif
                                                <br />
                                            @endforeach
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>暱稱：</td>
                                        <td>{{ $showUser->nickname }}</td>
                                    </tr>
                                    <tr>
                                        <td>用戶組：</td>
                                        <td>
                                            @foreach($showUser->roles as $role)
                                                {{ $role->display_name }}<br />
                                            @endforeach
                                        </td>
                                    </tr>
                                    @if(Entrust::hasRole('admin'))
                                        <tr>
                                            <td colspan="2" class="danger">
                                                以下僅管理員可見
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>社員資料：</td>
                                            <td>
                                                @if($showUser->member)
                                                    <a href="{{ URL::route('member.show', $showUser->member->id) }}">
                                                        {{ $showUser->member->realname }}
                                                        @if($showUser->member->nickname)
                                                            （{{ $showUser->member->nickname }}）
                                                        @endif
                                                    </a>
                                                @else
                                                    <span class="text-danger">尚未連結</span>
                                                @endif
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>註冊時間：</td>
                                            <td>{{ $showUser->register_at }}</td>
                                        </tr>
                                        <tr>
                                            <td>註冊IP：</td>
                                            <td>{{ $showUser->register_ip }}</td>
                                        </tr>
                                        <tr>
                                            <td>最後登入時間：</td>
                                            <td>{{ $showUser->lastlogin_at }}</td>
                                        </tr>
                                        <tr>
                                            <td>最後登入IP：</td>
                                            <td>{{ $showUser->lastlogin_ip }}</td>
                                        </tr>
                                    @endif
                                </table>
                                @if(Entrust::hasRole('admin'))
                                    <div class="text-center">
                                        {!! HTML::linkRoute('user.edit-other-profile', '編輯資料', $showUser->id, ['class' => 'btn btn-primary']) !!}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection